// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, PrismaConfig } from "prisma/config";
import { PrismaPg } from "@prisma/adapter-pg";

export default defineConfig({
  schema: "src/prisma/schema/main.prisma",
  migrations: {
    path: "src/prisma/schema/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL!
  } 
} satisfies PrismaConfig
);
